# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Upload NuGet package to GitHub
      uses: actions/upload-artifact@v4.6.0
      with:
        name: package
        path: artifacts/package/release/*.nupkg

  release:
    runs-on: ubuntu-latest    
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps: 
    #Push NuGet package to GitHub packages
    - name: Download nuget package artifact
      uses: actions/download-artifact@v3.0.2
      with:
        name: package
        path: package
    - name: Prep packages
      run: dotnet nuget add source --username ${{ vars.USERNAME }} --password ${{ secrets.NUGET_PACKAGE_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ vars.USERNAME }}/index.json"
    - name: Push package to GitHub packages 
      if: needs.build.outputs.CommitsSinceVersionSource > 0 #Only release if there has been a commit/version change  
      run: dotnet nuget push package/*.nupkg --api-key ${{ secrets.NUGET_PACKAGE_TOKEN }} --source "github"
    
